import mongoose, { Schema, Document } from "mongoose";

export interface IVisitor extends Document {
  _id: mongoose.Types.ObjectId;
  visitorId: string; // generated by SDK
  websiteId: mongoose.Types.ObjectId;
  firstSeen: Date;
  lastSeen: Date;
  browser: string;
  os: string;
  device: "desktop" | "tablet" | "mobile";
  language: string;
  timezone: string;
  country: string;
  city: string;
  screenResolution: string;
}

const VisitorSchema = new Schema<IVisitor>(
  {
    visitorId: {
      type: String,
      required: true,
      index: true,
    },
    websiteId: {
      type: Schema.Types.ObjectId,
      ref: "Website",
      required: true,
      index: true,
    },
    firstSeen: {
      type: Date,
      default: Date.now,
    },
    lastSeen: {
      type: Date,
      default: Date.now,
    },
    browser: {
      type: String,
      default: "Unknown",
    },
    os: {
      type: String,
      default: "Unknown",
    },
    device: {
      type: String,
      enum: ["desktop", "tablet", "mobile"],
      default: "desktop",
    },
    language: {
      type: String,
      default: "en",
    },
    timezone: {
      type: String,
      default: "UTC",
    },
    country: {
      type: String,
      default: "Vietnam",
    },
    city: {
      type: String,
      default: "Local",
    },
    screenResolution: {
      type: String,
      default: "Unknown",
    },
  },
  { timestamps: true }
);

// Unique composite index to avoid duplicate records for the same visitor on a single website
VisitorSchema.index({ visitorId: 1, websiteId: 1 }, { unique: true });

export const Visitor = mongoose.models.Visitor || mongoose.model<IVisitor>("Visitor", VisitorSchema);
export default Visitor;
